# Generated by Django 4.0.1 on 2022-01-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hplace', '0002_board_contents1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='contents1',
        ),
    ]
