# Generated by Django 4.0.1 on 2022-01-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hplace', '0003_remove_board_contents1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='like',
        ),
        migrations.AlterField(
            model_name='board',
            name='contents',
            field=models.CharField(max_length=200),
        ),
    ]
