# Generated by Django 4.0.1 on 2022-01-20 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hplace', '0004_remove_board_like_alter_board_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='menu_1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='board',
            name='menu_2',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='board',
            name='menu_3',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='board',
            name='menu_4',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='board',
            name='menu_5',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='board',
            name='price_1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='board',
            name='price_2',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='board',
            name='price_3',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='board',
            name='price_4',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='board',
            name='price_5',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='board',
            name='contents',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='board',
            name='user_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='board',
            name='user_food',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='board',
            name='user_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='board',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
